"""add pending_signups and email_verified

Revision ID: 3fd72fb06c69
Revises: 36410693368f
Create Date: 2026-05-10 14:35:06.712140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd72fb06c69'
down_revision: Union[str, None] = '36410693368f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_signups_email'), 'pending_signups', ['email'], unique=True)
    op.create_index(op.f('ix_pending_signups_expires_at'), 'pending_signups', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pending_signups_id'), 'pending_signups', ['id'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_pending_signups_id'), table_name='pending_signups')
    op.drop_index(op.f('ix_pending_signups_expires_at'), table_name='pending_signups')
    op.drop_index(op.f('ix_pending_signups_email'), table_name='pending_signups')
    op.drop_table('pending_signups')
    # ### end Alembic commands ###
