"""create exercises and plan tables

Revision ID: 4c2370eef11e
Revises: a93659e58fce
Create Date: 2026-05-09 23:40:53.303219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c2370eef11e'
down_revision: Union[str, None] = 'a93659e58fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_day_exercises')
    op.drop_table('plan_days')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_table('exercises')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('muscle_primary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('muscles_secondary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('equipment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sets_default', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps_default', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('demo_video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tutorial_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movement_pattern', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('program_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_plans_pkey'))
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('plan_days',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('muscles', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_est', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('plan_days_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_days_pkey'))
    )
    op.create_table('plan_day_exercises',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan_day_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rest_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tempo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('plan_day_exercises_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_days.id'], name=op.f('plan_day_exercises_plan_day_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_day_exercises_pkey'))
    )
    # ### end Alembic commands ###
