from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models.exercise import Exercise

SEED_EXERCISES = [
    {"id": "ex_001", "name": "Barbell Bench Press", "muscle_primary": "Chest", "muscles_secondary": ["Triceps", "Shoulders"], "difficulty": "Intermediate", "equipment": "Barbell", "sets_default": 4, "reps_default": 10, "rest_seconds": 90, "movement_pattern": "horizontal_push", "description": "Lie on a flat bench and press the barbell from chest to full arm extension."},
    {"id": "ex_002", "name": "Incline Dumbbell Press", "muscle_primary": "Chest", "muscles_secondary": ["Shoulders", "Triceps"], "difficulty": "Intermediate", "equipment": "Dumbbell", "sets_default": 3, "reps_default": 12, "rest_seconds": 75, "movement_pattern": "horizontal_push", "description": "Press dumbbells upward on an incline bench set to 30-45 degrees."},
    {"id": "ex_003", "name": "Overhead Shoulder Press", "muscle_primary": "Shoulders", "muscles_secondary": ["Triceps"], "difficulty": "Intermediate", "equipment": "Barbell", "sets_default": 4, "reps_default": 8, "rest_seconds": 90, "movement_pattern": "vertical_push", "description": "Press the barbell overhead from shoulder height to full arm extension."},
    {"id": "ex_004", "name": "Lateral Raises", "muscle_primary": "Shoulders", "muscles_secondary": ["Traps"], "difficulty": "Beginner", "equipment": "Dumbbell", "sets_default": 3, "reps_default": 15, "rest_seconds": 60, "movement_pattern": "isolation", "description": "Raise dumbbells to the sides until arms are parallel to the floor."},
    {"id": "ex_005", "name": "Triceps Rope Pushdown", "muscle_primary": "Arms", "muscles_secondary": [], "difficulty": "Beginner", "equipment": "Cable", "sets_default": 3, "reps_default": 12, "rest_seconds": 60, "movement_pattern": "isolation", "description": "Push the rope attachment down from chest height until arms are fully extended."},
    {"id": "ex_006", "name": "Cable Chest Fly", "muscle_primary": "Chest", "muscles_secondary": ["Shoulders"], "difficulty": "Intermediate", "equipment": "Cable", "sets_default": 3, "reps_default": 12, "rest_seconds": 60, "movement_pattern": "isolation", "description": "Bring cable handles together in front of chest with a slight elbow bend."},
    {"id": "ex_007", "name": "Pull-ups", "muscle_primary": "Back", "muscles_secondary": ["Biceps", "Core"], "difficulty": "Intermediate", "equipment": "Bodyweight", "sets_default": 4, "reps_default": 8, "rest_seconds": 90, "movement_pattern": "vertical_pull", "description": "Hang from a bar and pull your body up until chin clears the bar."},
    {"id": "ex_008", "name": "Barbell Row", "muscle_primary": "Back", "muscles_secondary": ["Biceps", "Core"], "difficulty": "Intermediate", "equipment": "Barbell", "sets_default": 4, "reps_default": 10, "rest_seconds": 90, "movement_pattern": "horizontal_pull", "description": "Hinge at the hips and row the barbell to your lower chest."},
    {"id": "ex_009", "name": "Seated Cable Row", "muscle_primary": "Back", "muscles_secondary": ["Biceps"], "difficulty": "Beginner", "equipment": "Cable", "sets_default": 3, "reps_default": 12, "rest_seconds": 75, "movement_pattern": "horizontal_pull", "description": "Pull the cable handle toward your lower chest while seated."},
    {"id": "ex_010", "name": "Face Pulls", "muscle_primary": "Shoulders", "muscles_secondary": ["Traps", "Back"], "difficulty": "Beginner", "equipment": "Cable", "sets_default": 3, "reps_default": 15, "rest_seconds": 60, "movement_pattern": "horizontal_pull", "description": "Pull the rope toward your face with elbows high."},
    {"id": "ex_011", "name": "Barbell Bicep Curl", "muscle_primary": "Arms", "muscles_secondary": [], "difficulty": "Beginner", "equipment": "Barbell", "sets_default": 3, "reps_default": 12, "rest_seconds": 60, "movement_pattern": "isolation", "description": "Curl the barbell from hip height to shoulder height."},
    {"id": "ex_012", "name": "Hammer Curl", "muscle_primary": "Arms", "muscles_secondary": ["Forearms"], "difficulty": "Beginner", "equipment": "Dumbbell", "sets_default": 3, "reps_default": 12, "rest_seconds": 60, "movement_pattern": "isolation", "description": "Curl dumbbells with neutral grip (palms facing each other)."},
    {"id": "ex_013", "name": "Barbell Squat", "muscle_primary": "Legs", "muscles_secondary": ["Glutes", "Core"], "difficulty": "Intermediate", "equipment": "Barbell", "sets_default": 4, "reps_default": 8, "rest_seconds": 120, "movement_pattern": "squat", "description": "Squat down with barbell on upper back until thighs are parallel to floor."},
    {"id": "ex_014", "name": "Romanian Deadlift", "muscle_primary": "Legs", "muscles_secondary": ["Back", "Glutes"], "difficulty": "Intermediate", "equipment": "Barbell", "sets_default": 4, "reps_default": 10, "rest_seconds": 90, "movement_pattern": "hinge", "description": "Hinge at the hips with slight knee bend, lowering barbell along the legs."},
    {"id": "ex_015", "name": "Leg Press", "muscle_primary": "Legs", "muscles_secondary": ["Glutes"], "difficulty": "Beginner", "equipment": "Machine", "sets_default": 3, "reps_default": 12, "rest_seconds": 90, "movement_pattern": "squat", "description": "Push the platform away by extending your legs."},
    {"id": "ex_016", "name": "Leg Curl", "muscle_primary": "Legs", "muscles_secondary": [], "difficulty": "Beginner", "equipment": "Machine", "sets_default": 3, "reps_default": 12, "rest_seconds": 60, "movement_pattern": "isolation", "description": "Curl the pad toward your glutes while lying face down."},
    {"id": "ex_017", "name": "Calf Raises", "muscle_primary": "Legs", "muscles_secondary": [], "difficulty": "Beginner", "equipment": "Machine", "sets_default": 4, "reps_default": 15, "rest_seconds": 45, "movement_pattern": "isolation", "description": "Rise onto the balls of your feet against resistance."},
    {"id": "ex_018", "name": "Goblet Squat", "muscle_primary": "Legs", "muscles_secondary": ["Core", "Glutes"], "difficulty": "Beginner", "equipment": "Dumbbell", "sets_default": 3, "reps_default": 12, "rest_seconds": 75, "movement_pattern": "squat", "description": "Hold a dumbbell at chest height and squat to parallel."},
    {"id": "ex_019", "name": "Push-ups", "muscle_primary": "Chest", "muscles_secondary": ["Triceps", "Shoulders", "Core"], "difficulty": "Beginner", "equipment": "Bodyweight", "sets_default": 3, "reps_default": 15, "rest_seconds": 60, "movement_pattern": "horizontal_push", "description": "Lower your body to the floor and push back up with arms extended."},
    {"id": "ex_020", "name": "Dumbbell Row", "muscle_primary": "Back", "muscles_secondary": ["Biceps"], "difficulty": "Beginner", "equipment": "Dumbbell", "sets_default": 3, "reps_default": 12, "rest_seconds": 60, "movement_pattern": "horizontal_pull", "description": "Row a dumbbell to your hip while supported on a bench."},
    {"id": "ex_021", "name": "Plank", "muscle_primary": "Core", "muscles_secondary": ["Shoulders"], "difficulty": "Beginner", "equipment": "Bodyweight", "sets_default": 3, "reps_default": 1, "rest_seconds": 60, "movement_pattern": "isometric", "description": "Hold a straight body position on forearms and toes."},
    {"id": "ex_022", "name": "Hip Thrust", "muscle_primary": "Legs", "muscles_secondary": ["Glutes"], "difficulty": "Intermediate", "equipment": "Barbell", "sets_default": 4, "reps_default": 10, "rest_seconds": 90, "movement_pattern": "hinge", "description": "Drive hips upward with upper back on bench, barbell across hips."},
]


async def seed_exercises(db: AsyncSession):
    result = await db.execute(select(Exercise).limit(1))
    if result.scalar_one_or_none():
        return

    for ex_data in SEED_EXERCISES:
        db.add(Exercise(**ex_data))
    await db.commit()
